Add Turkish translation
coteditor/coteditor.github.io pull request #17
Opened 2022-03-05 10:14 UTC by bitigchi

2022-03-19 02:51 UTC, 1024jp requested changes
Thank you for the PR. However, could you remove beta.tr.html and cot.tr.html because these pages are less page views by normal users and too much to maintain multiple languages (I don't provide them in Japanese as well)? After the change, I'll marge this.

2022-03-19 12:33 UTC, bitigchi commented
> 
> Thank you for the PR. However, could you remove beta.tr.html and cot.tr.html because these pages are less page views by normal users and too much to maintain multiple languages (I don't provide them in Japanese as well)? After the change, I'll marge this.

Done! Thanks for the update.

2022-03-20 10:58 UTC, 1024jp approved these changes

2022-03-20 10:58 UTC, merged

2022-03-20 10:58 UTC, 1024jp commented
Thank you!