Add translated CSS element
coteditor/coteditor.github.io pull request #19
Opened 2022-03-20 12:00 UTC by bitigchi

This localises the `Q.` and `A.` CSS elements.

2022-03-20 12:57 UTC, 1024jp requested changes

2022-03-20 12:57 UTC, 1024jp commented on css/common.css
> +}
Here (and the same for 'Y.' below), you don't need to set the `color` again. Just setting `content` is enough.

2022-03-20 16:22 UTC, bitigchi commented
> 
> In css/common.css:
> 
> > +dl.fqa > dt:lang(tr)::before {
> +	content: 'S.';
> +	color: hsl(200,60%,45%);
> +}
> +dl.fqa > dd:lang(tr)::before {
> +	content: 'Y.';
> +	color: hsl(30,75%,45%);
> +}
> 
> Here (and the same for 'Y.' below), you don't need to set the color again. Just setting content is enough.

Done!

2022-03-21 06:30 UTC, 1024jp approved these changes

2022-03-21 06:30 UTC, merged